import os
import asyncio
import logging
from typing import List, Dict
from dotenv import load_dotenv

# Setup environment and logging
load_dotenv()
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

# In a real-world implementation, import your LLM client (e.g., OpenAI) and set the model.
# For this demonstration, we'll simulate the LLM responses.
# Example:
# from openai import OpenAI
# client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
# model = "gpt-4o-mini"

# ------------------------------------------------------------------
# Simulated asynchronous LLM call
# ------------------------------------------------------------------
async def call_llm(prompt: str) -> str:
    """
    Simulate an asynchronous LLM call.
    In production, this function would call the LLM's async API (e.g., openai.ChatCompletion.acreate).
    """
    logger.info(f"Calling LLM with prompt:\n{prompt}\n")
    await asyncio.sleep(0.5)  # Simulate network latency

    # Simple simulation based on prompt content:
    if "Next Question:" in prompt:
        # If the conversation transcript includes the word 'fever' for demonstration, ask a follow-up.
        if "fever" in prompt.lower():
            return "Do you notice any changes in the child's appetite?"
        else:
            return "Done"
    elif "diagnostic report" in prompt.lower():
        # Simulate a final markdown report
        return (
            "**Diagnosis**\nAcute Viral Infection\n\n"
            "**Treatment**\n- Ensure proper hydration\n- Rest the child\n\n"
            "**Disclosure reminder**\nThis information is provided by an AI and is not a substitute for professional advice.\n\n"
            "**Revisit the conversation**\nYou may refer back to this conversation anytime for further clarification.\n\n"
            "**Product recommendations**\n- Thermometer\n- Pediatric electrolyte solution\n\n"
            "**This tool is supported by people. [Make a donation to support this tool](https://buy.stripe.com/your-donation-link)**"
        )
    else:
        # For initial/fallback responses
        return "What is the primary symptom you have noticed?"

# ------------------------------------------------------------------
# Pediatric Diagnostic Workflow
# ------------------------------------------------------------------
class PediatricDiagnosticWorkflow:
    """
    A diagnostic workflow that:
      1. Starts with an initial question about the child's condition.
      2. Iteratively asks clarifying questions generated by an LLM based on the conversation transcript.
      3. Concludes when the LLM signals completion by responding with "Done" (or an empty response).
      4. Generates a final markdown report including diagnosis, treatment, a disclaimer, and product recommendations.
    """
    def __init__(self) -> None:
        self.conversation: List[Dict[str, str]] = []
        self.initial_question: str = "What seems to be the issue with the child or infant?"
    
    async def run(self) -> None:
        """Run the entire diagnostic conversation."""
        await self.ask_initial_question()
        await self.ask_followup_questions()
        report = await self.generate_final_report()
        print("\nFinal Diagnostic Report:\n")
        print(report)
    
    async def ask_initial_question(self) -> None:
        """Ask the static initial question and record the response."""
        print(self.initial_question)
        answer = input("Your response: ")
        self.conversation.append({"question": self.initial_question, "answer": answer})
    
    async def ask_followup_questions(self) -> None:
        """Continuously ask follow-up questions until no further clarification is needed."""
        while True:
            next_question = await self.get_llm_next_question()
            if not next_question or next_question.strip().lower() == "done":
                logger.info("No further questions. Ending conversation.")
                break
            print(next_question)
            answer = input("Your response: ")
            self.conversation.append({"question": next_question, "answer": answer})
    
    async def get_llm_next_question(self) -> str:
        """Generate the next clarifying question using the LLM, based on the current conversation transcript."""
        transcript = self.build_transcript()
        prompt = (
            "You are a pediatrician assisting in a diagnostic conversation with a parent. "
            "Based on the conversation transcript below, ask the next concise and clarifying question necessary to complete the diagnosis. "
            "Ask only one question. If no further clarification is needed, simply respond with 'Done'.\n\n"
            f"Conversation Transcript:\n{transcript}\n\nNext Question:"
        )
        try:
            response = await call_llm(prompt)
            logger.info(f"LLM generated follow-up question: {response}")
            return response.strip()
        except Exception as e:
            logger.exception("Error during LLM call for next question")
            return "Done"
    
    def build_transcript(self) -> str:
        """Build a text transcript from the conversation history."""
        return "\n".join(
            f"Q: {entry['question']}\nA: {entry['answer']}"
            for entry in self.conversation
        )
    
    async def generate_final_report(self) -> str:
        """Generate a final markdown report using the LLM."""
        transcript = self.build_transcript()
        prompt = (
            "Based on the following conversation with a parent regarding their child's health, produce a structured, "
            "markdown formatted diagnostic report. The report must include the sections below and follow the exact format:\n\n"
            "**Diagnosis**\n{Diagnosis}\n\n"
            "**Treatment**\n{Treatment}\n\n"
            "You can also check [pharmacies open now](https://www.google.com/maps/search/pharmacies+open+now/).\n\n"
            "**Disclosure reminder**\nThis information is provided 100% by an AI and should not replace a consultation with a healthcare provider.\n\n"
            "**Revisit the conversation**\nPlease revisit our conversation anytime if you still have questions or need another diagnostic for your child.\n\n"
            "**Product recommendations**\n{Product_recommendations}\n\n"
            "**This tool is supported by people. [Make a donation to support this tool](https://buy.stripe.com/your-donation-link)**\n\n"
            f"Conversation Transcript:\n{transcript}\n"
        )
        try:
            response = await call_llm(prompt)
            logger.info("Final report generated successfully.")
            return response.strip()
        except Exception as e:
            logger.exception("Error during LLM call for final report")
            return "An error occurred while generating the final report."

# ------------------------------------------------------------------
# Main Execution
# ------------------------------------------------------------------
async def main() -> None:
    workflow = PediatricDiagnosticWorkflow()
    await workflow.run()

if __name__ == "__main__":
    asyncio.run(main())
